backend:
  name: github
  repo: egorasus/mihey-portfolio
  branch: main
  base_url: https://mihey-portfolio.pages.dev
  auth_endpoint: /oauth/callback

media_folder: uploads
public_folder: /uploads

locale: ru

collections:
  - name: nav
    label: Навигация и контакты
    files:
      - label: Настройки
        name: settings
        file: data/settings.json
        fields:
          - label: 'Ссылка "Связаться"'
            name: contact_url
            widget: string
            default: "#"
          - label: Instagram
            name: instagram_url
            widget: string
            default: "#"
          - label: Instagram текст
            name: instagram_label
            widget: string
            default: Instagram
          - label: LinkedIn
            name: linkedin_url
            widget: string
            default: "#"
          - label: LinkedIn текст
            name: linkedin_label
            widget: string
            default: LinkedIn
          - label: Contact email
            name: contact_email
            widget: string
            default: "hello [at] miheysound.com"

  - name: tags
    label: Теги
    files:
      - label: Список тегов
        name: tags
        file: data/tags.json
        fields:
          - label: Теги
            name: tags
            widget: list
            label_singular: Тег
            fields:
              - { label: Название, name: label, widget: string }
              - { label: Значение (латиницей), name: value, widget: string }

  - name: projects
    label: Проекты
    files:
      - label: Список проектов
        name: projects
        file: data/projects.json
        fields:
          - label: Проекты
            name: projects
            widget: list
            label_singular: Проект
            fields:
              - { label: Название, name: title, widget: string }
              - { label: Подзаголовок, name: subtitle, widget: string }
              - { label: Год, name: year, widget: string }
              - label: Теги
                name: tags
                widget: list
                field: { label: Тег, name: tag, widget: string }
              - { label: Описание, name: details, widget: text }
              - { label: Обложка, name: cover, widget: image }
              - label: Услуги
                name: services
                widget: list
                field: { label: Услуга, name: service, widget: string }
              - label: Фотографии
                name: images
                widget: list
                field: { label: Изображение, name: image, widget: image }
              - label: Кредиты
                name: credits
                widget: list
                fields:
                  - { label: Роль, name: role, widget: string }
                  - { label: Имя, name: name, widget: string }